    - os: osx
      language: sh
      name: "osX Python 3.8"
      python: "3.8"
      osx_image: xcode11.4
      env:
        # on osx pip and python points to python 2.7 - therefore we have to use pip3 and python3 here
        - python_command="python3"
        - pip_command="python3 -m pip"
