    - os: linux
      language: python
      python: '3.5'

    - os: linux
      language: python
      python: '3.6'

    - os: linux
      language: python
      python: '3.7'

    - os: linux
      language: python
      python: '3.8'
      before_install:
          - export mypy_static_typecheck="True"
          - export build_docs="True"
          - export deploy_on_pypi="True"

    - os: linux
      language: python
      python: '3.8-dev'
